package generate

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/thatguystone/cog/assert"
	"golang.org/x/tools/imports"
)

type Buffer struct {
	bytes.Buffer
	dstPath string
}

func New() *Buffer {
	const (
		cmdSuffix = ".cmd.go"
		outSuffix = ".out.go"
	)

	srcPath := os.Getenv("GOFILE")
	if !strings.HasSuffix(srcPath, cmdSuffix) {
		panic(
			fmt.Errorf(
				`generate cmd %q must have a name in the form of "*.cmd.go"`,
				srcPath,
			),
		)
	}

	b := &Buffer{
		dstPath: strings.TrimSuffix(srcPath, cmdSuffix) + outSuffix,
	}

	fmt.Fprintf(b, "// Code generated by `go generate %s`. DO NOT EDIT.\n", srcPath)
	fmt.Fprintln(b)

	wd, err := os.Getwd()
	assert.Nil(err)
	pkg := filepath.Base(wd)

	fmt.Fprintf(b, "package %s\n", pkg)
	fmt.Fprintln(b)

	return b
}

func (b *Buffer) WriteFile() {
	out, err := imports.Process(b.dstPath, b.Bytes(), nil)
	assert.Nil(err)

	err = os.WriteFile(b.dstPath, out, 0640)
	assert.Nil(err)
}
